### ISSUE TITLE
Please expand wiki

### ISSUE THREAD

**Issue by BillWoodNHS** [NELCSU/PSCleaner#13]
Please can the wiki be updated to include overarching detail on how the tool works? i.e. how the tool uses the inbuilt reference data to effectively pseudonymise/redact substrings of data. 
Particularly with reference to the different rules used for each given substring/data type (names, addresses, dates, phone numbers, emails, postcodes, financial information)

**Comment by ibuckner** [comment]
@BillWoodNHS Good point, I'll set aside soon time soon to do one final refresh of the wiki pages to reflect some of the new (old) screen content and features.

**Comment by ibuckner** [comment]
Updated wiki to expand on the template definition section, with some additional context and screenshots
